### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by georgefst** [georgefst/monpad#20]
- [ ] Dhall
  - [ ] Diamond dependency issue causes huge blowup in size of fully-resolved files. Would be awesome if those were instead small and readable. This could be something we could work around using the existing Haskell API.
  - [ ] Deserialising existentials. Even though, without `--system-device`, we don't care what the type of axis and event data is, we can't accept a `Layout Axis Key` - it has to be a `Layout {} {}`. This is really awkward.
- [x] Streamly
  - [x] ~~We probably need https://github.com/composewell/streamly/issues/1203 fixed, especially when it comes to releasing as a library and exposing `ServerConfig.onUpdate`. For the executable, it's possible we only use it safely, aside from the error handling issues.~~ EDIT: It's fine, we work around this safely in d9929bdbcc0f3c7578314b7cc115a8008e0a31f9
- [ ] documentation 
  - [ ] should be clear what all CLI flags do
  - [ ] #1

When all that's done, we can set up #7, and announce in a few places (r/madeinhaskell? hacker news?).

We can also release on Hackage, with the pre-compiled JS from Elm etc. Though we'll have to have a think about how we handle the platform-specific `default.dhall`, and the `release` flag.
